title: LegoLib
description: Enhancing the FabricMC Experience
theme: just-the-docs

url: https://legolib-fabric.github.io
  
nav_external_links:
  - title: Curseforge
    url: https://www.curseforge.com/minecraft/mc-mods/legolib
  - title: Github
    url: https://github.com/LegoLib-Fabric
  - title: Issues
    url: https://github.com/LegoLib-Fabric/LegoLib/issues
  - title: Resources
    url: https://github.com/LegoLib-Fabric/community

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

enable_copy_code_button: true

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

footer_content: "Copyright &copy; 2023 Daniel-Tayden Larsen.  |  We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with Mojang AB or Microsoft."