title: LegoLib for Fabric
description: Enhancing the FabricMC Experience
theme: just-the-docs

url: https://legolib-fabric.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
