title: LegoLib
description: Enhancing the FabricMC Experience
theme: just-the-docs

url: https://legolib-fabric.github.io
  
nav_external_links:
  - title: Curseforge
    url: https://www.curseforge.com/minecraft/mc-mods/legolib
  - title: Github
    url: https://github.com/LegoLib-Fabric
  - title: Issues
    url: https://github.com/LegoLib-Fabric/LegoLib/issues
  - title: Resources
    url: https://github.com/LegoLib-Fabric/community

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

enable_copy_code_button: true

callouts:
  warning:
    title: WARNING
    color: red
  important:
    title: IMPORTANT
    color: purple
  note:
    title: NOTE
    color: purple
  recommendedtools:
    title: RECOMMENDED TOOLS
    color: green
  requires:
    title: REQUIRES
    color: yellow

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: dark

footer_content: "LegoLib Documentation is licensed under the CC-BY 4.0 license.</br></br>Copyright &copy; 2023 Daniel-Tayden Larsen.</br>We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with Mojang AB and/or Microsoft."